#!/bin/bash

# WebRecon Tool User Guide
# This script demonstrates how to use the WebRecon tool with examples

echo "WebRecon Tool - User Guide"
echo "=========================="
echo ""
echo "This guide will help you understand how to use the WebRecon tool effectively."
echo ""

echo "1. Basic Scan"
echo "-------------"
echo "To perform a basic scan on a target domain:"
echo "./webrecon scan -t example.com"
echo ""
echo "This will perform a full scan including reconnaissance, port scanning,"
echo "technology fingerprinting, vulnerability scanning, and directory brute forcing."
echo ""

echo "2. Reconnaissance Only"
echo "---------------------"
echo "To perform only reconnaissance (WHOIS, DNS, SSL, subdomains):"
echo "./webrecon recon -t example.com"
echo ""

echo "3. Specific Scans"
echo "----------------"
echo "To perform specific types of scans:"
echo ""
echo "Port scanning:"
echo "./webrecon portscan -t example.com"
echo ""
echo "Technology fingerprinting:"
echo "./webrecon fingerprint -t example.com"
echo ""
echo "Vulnerability scanning:"
echo "./webrecon vulnscan -t example.com"
echo ""
echo "Directory brute forcing:"
echo "./webrecon dirbrute -t example.com"
echo ""

echo "4. Output Formats"
echo "----------------"
echo "You can generate reports in different formats:"
echo ""
echo "JSON format (for machine processing):"
echo "./webrecon scan -t example.com -f json -o results"
echo ""
echo "Markdown format (default, for documentation):"
echo "./webrecon scan -t example.com -f md -o results"
echo ""
echo "HTML format (for browser viewing):"
echo "./webrecon scan -t example.com -f html -o results"
echo ""

echo "5. Performance Tuning"
echo "-------------------"
echo "You can adjust the number of concurrent threads:"
echo "./webrecon scan -t example.com -j 20"
echo ""
echo "Higher values increase speed but may trigger rate limiting or overload the target."
echo ""

echo "6. Custom Wordlists"
echo "-----------------"
echo "You can use custom wordlists for subdomain enumeration and directory brute forcing:"
echo "./webrecon scan -t example.com -w /path/to/wordlist.txt"
echo ""

echo "7. Verbose Output"
echo "---------------"
echo "For detailed output during scanning:"
echo "./webrecon scan -t example.com -v"
echo ""

echo "8. Help"
echo "------"
echo "To see all available commands and options:"
echo "./webrecon help"
echo ""

echo "Remember to use this tool responsibly and only on systems you have permission to scan."
echo ""
